services:
  - type: web
    name: college-management
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_DIALECT
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: college-management-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: college-management-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: college-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: college-management-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: college-management-db
          property: port

databases:
  - name: college-management-db
    engine: postgres
    plan: free
    version: latest
